-- Migration: 013_vsl_activity_catalog.sql
-- Purpose: (1) Turn Completion into a real enum (0/20/50/75/100), replacing
--          the old free 0-100 numeric input; (2) promote "Area covered" out
--          of activity_properties jsonb into its own real column; (3) create
--          a data-driven activity catalog (vsl_activity_types /
--          vsl_activity_type_properties / vsl_activity_common_fields) so the
--          webmap's Log Activity form and the dashboard's Add/Edit Activity
--          forms both read the same 17 activities + their extra properties
--          from the database, instead of each hardcoding its own JS copy of
--          the list (which is what let them drift out of sync).
--
-- Applied directly against the live "victoriasugar" Supabase project
-- (knhgliyghacvkeeptsfl) via the Supabase MCP; recorded here so the sql/
-- folder stays a faithful history of the schema.

-- ── 1. Completion enum ──────────────────────────────────────────────────
-- Round the two existing rows that predate the enum to their nearest
-- allowed value, then enforce it going forward. NULL (no progress logged)
-- stays allowed.
update public.vsl_activities set completion_value = 20 where completion_value = 18;
update public.vsl_activities set completion_value = 20 where completion_value = 25;

alter table public.vsl_activities
  add constraint vsl_activities_completion_value_chk
  check (completion_value is null or completion_value = any (array[0,20,50,75,100]::numeric[]));

-- ── 2. Area covered — promote out of activity_properties jsonb ─────────
alter table public.vsl_activities add column if not exists area_covered_acres numeric;

update public.vsl_activities
set area_covered_acres = (activity_properties->>'area_covered_acres')::numeric
where activity_properties ? 'area_covered_acres' and area_covered_acres is null;

update public.vsl_activities
set activity_properties = activity_properties - 'area_covered_acres'
where activity_properties ? 'area_covered_acres';

comment on column public.vsl_activities.area_covered_acres is
  'Area (in acres) actually covered so far when an activity is logged at less than 100% completion. Null/irrelevant once completion_value = 100.';

-- ── 3. Activity catalog tables ──────────────────────────────────────────
create table if not exists public.vsl_activity_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vsl_activity_type_properties (
  id bigint generated by default as identity primary key,
  activity_type_id bigint not null references public.vsl_activity_types(id) on delete cascade,
  key text not null,
  label text not null,
  data_type text not null check (data_type in ('text','number','date','select','textarea')),
  options jsonb,
  option_labels jsonb,
  show_when jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (activity_type_id, key)
);

create table if not exists public.vsl_activity_common_fields (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label text not null,
  data_type text not null check (data_type in ('text','number','date','select','textarea')),
  options jsonb,
  option_labels jsonb,
  show_when jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_vsl_activity_type_properties_type_id on public.vsl_activity_type_properties(activity_type_id);

alter table public.vsl_activity_types enable row level security;
alter table public.vsl_activity_type_properties enable row level security;
alter table public.vsl_activity_common_fields enable row level security;

create policy "activity_types read all" on public.vsl_activity_types for select to authenticated using (true);
create policy "activity_types read anon" on public.vsl_activity_types for select to anon using (true);
create policy "activity_types write admin_surveyor" on public.vsl_activity_types for all to authenticated
  using (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'))
  with check (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'));

create policy "activity_type_properties read all" on public.vsl_activity_type_properties for select to authenticated using (true);
create policy "activity_type_properties read anon" on public.vsl_activity_type_properties for select to anon using (true);
create policy "activity_type_properties write admin_surveyor" on public.vsl_activity_type_properties for all to authenticated
  using (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'))
  with check (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'));

create policy "activity_common_fields read all" on public.vsl_activity_common_fields for select to authenticated using (true);
create policy "activity_common_fields read anon" on public.vsl_activity_common_fields for select to anon using (true);
create policy "activity_common_fields write admin_surveyor" on public.vsl_activity_common_fields for all to authenticated
  using (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'))
  with check (vsl_is_role('ADMIN') or vsl_is_role('SURVEYOR'));

-- ── 4. Seed: the 17 activity types ──────────────────────────────────────
insert into public.vsl_activity_types (name, sort_order) values
  ('Bush Clearing',1),('Ploughing',2),('Harrow',3),('Ripping',4),('Ridging',5),
  ('Furrowing',6),('Lime Application',7),('Planting',8),('Manuring',9),
  ('Fertilization',10),('Weeding',11),('Spraying',12),('Irrigation',13),
  ('Harvesting',14),('Loading',15),('Trash Lining',16),('Trash Collection',17)
on conflict (name) do update set sort_order = excluded.sort_order;

-- ── 5. Seed: fields shared by every activity ────────────────────────────
insert into public.vsl_activity_common_fields (key, label, data_type, options, option_labels, show_when, sort_order) values
  ('team_size','Team size','number',null,null,null,1),
  ('number_of_machines','Number of machines','number',null,null,null,2),
  ('completion_value','Progress (%)','select','["0","20","50","75","100"]','["0%","20%","50%","75%","100%"]',null,3),
  ('area_covered_acres','Area covered (ac)','number',null,null,'{"key":"completion_value","notEquals":"100"}',4),
  ('comments','Comments','textarea',null,null,null,5),
  ('challenges','Challenges','textarea',null,null,null,6)
on conflict (key) do update set
  label = excluded.label, data_type = excluded.data_type, options = excluded.options,
  option_labels = excluded.option_labels, show_when = excluded.show_when, sort_order = excluded.sort_order;

-- ── 6. Seed: per-activity extra properties (formerly ACTIVITY_PROPERTY_DEFS
--      in js/map-app.js, duplicated separately as free-form fields the
--      dashboard never even rendered) ─────────────────────────────────────
insert into public.vsl_activity_type_properties (activity_type_id, key, label, data_type, options, option_labels, sort_order)
select t.id, v.key, v.label, v.data_type, v.options::jsonb, null, v.sort_order
from (values
  ('Bush Clearing','vegetation_density','Vegetation density','select','["Light","Medium","Heavy"]',1),
  ('Bush Clearing','clearing_depth','Clearing depth','select','["Surface clearing only","Includes stump & root removal"]',2),
  ('Bush Clearing','disposal_method','Disposal method','select','["Burning","Piling","Mulching in place","Hauled away"]',3),
  ('Bush Clearing','land_type','Land type','select','["New land","Fallow reclamation"]',4),
  ('Bush Clearing','machine_type','Machine type','select','["Bulldozer","Brush cutter","Tractor + slasher","Excavator","Other"]',5),
  ('Bush Clearing','fuel_used_litres','Fuel used (litres)','number',null,6),
  ('Bush Clearing','hours_worked','Hours worked','number',null,7),
  ('Ploughing','plough_type','Plough type','select','["First","Second","Third"]',1),
  ('Ploughing','implement_used','Implement used','select','["Disc plough","Moldboard plough","Chisel plough"]',2),
  ('Ploughing','plough_depth_cm','Plough depth (cm)','number',null,3),
  ('Ploughing','soil_moisture_condition','Soil moisture condition','select','["Dry","Moist","Wet"]',4),
  ('Ploughing','fuel_used_litres','Fuel used (litres)','number',null,5),
  ('Ploughing','hours_worked','Hours worked','number',null,6),
  ('Ploughing','operator_name','Operator name','text',null,7),
  ('Harrow','type','Type','select','["Disc harrow","Spike-tooth harrow","Tine harrow","Rotary harrow"]',1),
  ('Harrow','harrow_depth_cm','Harrow depth (cm)','number',null,2),
  ('Harrow','soil_moisture_condition','Soil moisture condition','select','["Dry","Moist","Wet"]',3),
  ('Harrow','fuel_used_litres','Fuel used (litres)','number',null,4),
  ('Harrow','hours_worked','Hours worked','number',null,5),
  ('Harrow','operator_name','Operator name','text',null,6),
  ('Ripping','ripping_depth_cm','Ripping depth (cm)','number',null,1),
  ('Ripping','rip_line_spacing_m','Rip line spacing (m)','number',null,2),
  ('Ripping','fuel_used_litres','Fuel used (litres)','number',null,3),
  ('Ripping','hours_worked','Hours worked','number',null,4),
  ('Ripping','operator_name','Operator name','text',null,5),
  ('Ridging','spacing_m','Spacing (m)','number',null,1),
  ('Ridging','ridge_height_cm','Ridge height (cm)','number',null,2),
  ('Ridging','ridge_width_cm','Ridge width (cm)','number',null,3),
  ('Ridging','fuel_used_litres','Fuel used (litres)','number',null,4),
  ('Ridging','hours_worked','Hours worked','number',null,5),
  ('Ridging','operator_name','Operator name','text',null,6),
  ('Furrowing','furrow_depth_cm','Furrow depth (cm)','number',null,1),
  ('Furrowing','furrow_spacing_m','Furrow spacing (m)','number',null,2),
  ('Furrowing','implement_used','Implement used','text',null,3),
  ('Furrowing','fuel_used_litres','Fuel used (litres)','number',null,4),
  ('Furrowing','hours_worked','Hours worked','number',null,5),
  ('Furrowing','operator_name','Operator name','text',null,6),
  ('Lime Application','lime_quantity_kg','Lime quantity (kg)','number',null,1),
  ('Lime Application','lime_type','Lime type/name','text',null,2),
  ('Lime Application','soil_ph_before','Soil pH before application','number',null,3),
  ('Lime Application','target_soil_ph','Target soil pH','number',null,4),
  ('Lime Application','incorporation_method','Incorporation method','select','["Ploughed in","Harrowed in","Left on surface"]',5),
  ('Planting','cane_variety','Cane variety','text',null,1),
  ('Planting','row_spacing_m','Row/sett spacing (m)','number',null,2),
  ('Planting','planting_depth_cm','Planting depth (cm)','number',null,3),
  ('Planting','weather_condition','Weather condition','select','["Sunny","Cloudy","Overcast","Rainy","Windy","Other"]',4),
  ('Manuring','manure_type','Manure type','select','["Farmyard manure","Compost","Poultry manure","Green manure"]',1),
  ('Manuring','quantity','Quantity','text',null,2),
  ('Fertilization','fertilizer_name','Fertilizer name','text',null,1),
  ('Fertilization','quantity','Quantity','text',null,2),
  ('Fertilization','application_type','Application type','select','["Basal","Top dressing","Foliar"]',3),
  ('Fertilization','npk_ratio','NPK ratio','text',null,4),
  ('Fertilization','weather_condition','Weather condition','text',null,5),
  ('Weeding','weeding_round','Weeding round','select','["1st","2nd","3rd+"]',1),
  ('Weeding','weed_pressure','Weed pressure','select','["Light","Medium","Heavy"]',2),
  ('Weeding','tools_used','Tools used','select','["Hoe","Machete","Cultivator","Other"]',3),
  ('Spraying','medicine_name','Medicine name (chemical/product)','text',null,1),
  ('Spraying','quantity','Quantity','text',null,2),
  ('Spraying','chemical_type','Chemical type','select','["Herbicide","Pesticide","Fungicide"]',3),
  ('Spraying','water_volume_litres','Water volume used (litres)','number',null,4),
  ('Spraying','application_equipment','Application equipment','select','["Knapsack sprayer","Boom sprayer","Drone","Tractor-mounted"]',5),
  ('Spraying','weather_condition','Weather condition','select','["Sunny","Cloudy","Overcast","Rainy","Windy","Other"]',6),
  ('Irrigation','litres_pumped','Litres pumped','number',null,1),
  ('Irrigation','water_source','Water source','text',null,2),
  ('Irrigation','duration_hours','Duration (hours)','number',null,3),
  ('Irrigation','fuel_used','Fuel used','text',null,4),
  ('Irrigation','operator_name','Operator name','text',null,5),
  ('Harvesting','yield_tonnes','Yield (tonnes)','number',null,1),
  ('Harvesting','brix_reading','Brix reading','number',null,2),
  ('Harvesting','transport_vehicle','Transport vehicle(s)','text',null,3),
  ('Harvesting','mill_destination','Mill destination','text',null,4),
  ('Harvesting','weather_condition','Weather condition','select','["Sunny","Cloudy","Overcast","Rainy","Windy","Other"]',5),
  ('Loading','loading_equipment','Loading equipment','select','["Grab loader","Crane","Manual"]',1),
  ('Loading','number_of_trucks','Number of trucks/trailers loaded','number',null,2),
  ('Loading','truck_registration_number','Truck registration number','text',null,3),
  ('Loading','destination_mill','Destination (mill name)','text',null,4),
  ('Trash Lining','purpose','Purpose','select','["Moisture retention","Weed suppression","Nutrient recycling"]',1),
  ('Trash Collection','disposal_method','Disposal method','select','["Burning","Composting","Baling","Hauled away","Mulching"]',1),
  ('Trash Collection','purpose','Purpose','select','["Land prep for next season","Sale","Biomass use"]',2),
  ('Trash Collection','transport_vehicle','Transport vehicle (if removed)','text',null,3)
) as v(activity_name, key, label, data_type, options, sort_order)
join public.vsl_activity_types t on t.name = v.activity_name
on conflict (activity_type_id, key) do update set
  label = excluded.label, data_type = excluded.data_type, options = excluded.options, sort_order = excluded.sort_order;

-- ── 7. activity_name: CHECK → FK against the catalog ────────────────────
-- Adding a new activity type going forward is now a single INSERT into
-- vsl_activity_types (plus its properties), not a migration touching this
-- constraint and two separate JS files.
alter table public.vsl_activities drop constraint if exists vsl_activities_activity_name_chk;
alter table public.vsl_activities
  add constraint vsl_activities_activity_name_fkey
  foreign key (activity_name) references public.vsl_activity_types(name);
